Revised mobility 2
monash-emu/AuTuMN pull request #201
Opened 2021-05-04 12:49 UTC by pavijayasundara

Added function to calculate vaccine infection and severity

2021-05-05 11:57 UTC, jtrauer commented
This looks great @pavijayasundara ! Sorry, but I think I should probably merge my branch in first and then get you to resolve the merge conflicts between this branch and the new version of master. There might also be some minor comments on how we should approach things here, but the general approach looks really good.

2021-05-10 01:52 UTC, MattSegal requested changes
Overall nice work, appreciate that you are contributing tests. Some feedback on what the tests are doing and coding style.

2021-05-10 01:52 UTC, MattSegal commented on apps/covid_19/model/parameters.py
> +    # infection_efficacy: float
Please don't comment out unused code - delete it instead.
It will be saved in version control history.

2021-05-10 01:52 UTC, MattSegal commented on apps/covid_19/model/preprocess/vaccination.py
> +    else:
Up to on how to write this you but I'd recommend breaking this large expression into multiple variables rather than many lines. Eg

```
prop_infected = 1. - vacc_prop_prevent_infection
prop_infect_prevented = 1. - (vacc_prop_prevent_infection * overall_efficacy)
severity_efficacy = overall_efficacy * prop_infected / prop_infect_prevented
```

I might have messed up the semantics there but that's the general idea. Typically using `\` to to multiline expressions is not "best practices" Python and the [auto-formatter](https://github.com/monash-emu/autumn#formatting) will strip this away eventually.

2021-05-10 01:52 UTC, MattSegal commented on tests/test_apps/test_vaccine_params.py
> +
Rather than using this test would be better to assert this at runtime in the Vaccination class in apps.covid_19.model.
You can see an example of this being done [here](https://github.com/monash-emu/AuTuMN/blob/master/apps/covid_19/model/parameters.py#L37)

This way the existing model building smoke tests would catch this issue.

So, for example, for overall_efficacy you might add to Vaccination:

```python
@validator("overall_efficacy", pre=True, allow_reuse=True)
def check_overall_efficacy(val):
	assert 0 <= val <= 1, "Overall efficacy should be in [0, 1]"
	return val
```

See here for more docs on pydantic validators: https://pydantic-docs.helpmanual.io/usage/validators/

2021-05-10 01:52 UTC, MattSegal commented on tests/test_apps/test_vaccine_params.py
> +
Given it's a determistic calculation, this test can be written with concrete values. For example

```python
VACCINE_PARAM_TESTS = [
	# overall_eff, vacc_prevention, infection_efficacy, severity_efficacy
	(0.1, 0.5, '???', '???'), # Hardcode expected results in '???'
	(0.77, 0.2, '???', '???'), # Hardcode expected results in '???'
	# Repeat until satisfied.
]


@pytest.mark.parametrize("overall_eff, vacc_prevention, infection_efficacy, severity_efficacy", VACCINE_PARAM_TESTS)
def test_vaccine_params(overall_eff, vacc_prevention, infection_efficacy, severity_efficacy):
    """
    Checking that converted parameters end up in the correct range, given sensible requests.
    """
    actual_infection_efficacy, actual_severity_efficacy = add_vaccine_infection_and_severity(vacc_prevention, overall_eff)
    assert actual_infection_efficacy == infection_efficacy
    assert actual_severity_efficacy == severity_efficacy
```

2021-05-10 01:53 UTC, MattSegal commented on tests/test_apps/test_vaccine_params.py
> +
If you like, you can then test that the validators throw AssertionErrors correctly, although that may not be necessary.

2021-05-10 06:13 UTC, merged